pdb_file: my_protein.pdb
prm_file: amoeba.prm
box:
  type: cube
  size: 55.0 # This would be overridden by the CLI flag above
salt_concentration: 0.15
ions:
  positive: NA
  negative: CL
output_prefix: my_protein_final